### ISSUE TITLE
Any plan to bump containerd-wasm-shims to 0.9.0?

### ISSUE THREAD

**Issue by thangchung** [KWasm/kwasm-node-installer#40]
Hi. Just wonder if contained-wasm-shims 0.9.0 has been released, so do we have any plan to bump it to 0.9.0 so that we can use `kwasm` to run the sidecar model with Istio or Dapr after?

https://github.com/KWasm/kwasm-node-installer/blob/main/images/installer/Dockerfile

**Comment by 0xE282B0** [comment]
Definitely!

The 0.9 release includes libcontainer and we need to test it on all cloud vendors. Some of them are using cgroups v1 😉

KWasm, at the moment, can only run WasmEdge with sidecars via crun. With the new shims I will change the default from crun to WasmEdge shim (and all the other shims). 

I will start testing next week after WasmCon.

**Comment by 0xE282B0** [comment]
Hi @thangchung,
I updated the installer to deislabs/containerd-wasm-shim 0.9.0 and containerd/runwasi `main` with this PR https://github.com/KWasm/kwasm-node-installer/pull/42. It removes crun in favor of the WasmEdge shim and all other shims can have sidecars, too. 

You can try it by changing the tag of the `installerImage` to the PR like this:
```
helm upgrade --install -n kwasm --create-namespace kwasm-operator kwasm/kwasm-operator \
  --set kwasmOperator.autoProvision="true" \
  --set kwasmOperator.installerImage="ghcr.io/kwasm/kwasm-node-installer:pr-42"
```

So far I only tested it on KinD but will continue testing during the week. I'd be happy to hear if it is working for you 😊

**Comment by 0xE282B0** [comment]
@thangchung, 0.3.0 installer has been released and is now available.
