### ISSUE TITLE
failed to install on GKE with node OS `Container-Optimized OS with containerd (cos_containerd)`

### ISSUE THREAD

**Issue by rajatjindal** [KWasm/kwasm-node-installer#56]
Hello folks, 

I was trying to use kwasm-operator on GKE cluster, and observed following error when using the default node pool image (Container-Optimized OS with containerd (cos_containerd))

The error from pod logs is:

```
mkdir: can't create directory '/mnt/node-root/opt/kwasm/': Read-only file system
```

update:

I noticed now that in the README only ubuntu machines are documented for GKE. so please feel to close if this error is expected and we don't intend to support this for now.

Thank you

**Comment by 0xE282B0** [comment]
Hi, exactly. COS has very high security standards and it was not possible for me to add binaries to the PATH or run files that are not in PATH folders. This seems to be a design decision by Google, so we can only support Ubuntu nodes on GKE.
